package main.exception;

public class BattleIsOverException extends Exception {
}
